### ISSUE TITLE
ant-design-vue: 使用a-input标签，控制台会打印警告。

### ISSUE THREAD

**Issue by Mako-Jin** [SanMako/strong-to-stop-view#5]
版本   
  "ant-design-vue": "^3.1.1",
  "vue": "^3.2.25",
问题描述：
  [Vue warn]: Failed setting prop "size" on <input>: value 0 is invalid. DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
截图：
![image](https://user-images.githubusercontent.com/103740507/163711809-381d2c55-c87e-4923-a378-6859bf15f6c4.png)
ant-design-vue issues 链接：
https://github.com/vueComponent/ant-design-vue/pull/5508

**Comment by LWD8** [comment]
"vue": "^3.2.25", 这个版本有提示警告。升级到"vue": "^3.2.31"倒没问题了

**Comment by Mako-Jin** [comment]
> "vue": "^3.2.25", 这个版本有提示警告。升级到"vue": "^3.2.31"倒没问题了

我试着降vue的版本到^3.2.31试一下。谢谢大佬。

**Comment by Mako-Jin** [comment]
大佬们已经修复问题了
